use crate::{
    game_models::{Health, Role, Season, Side, Speed},
    operator::{Operator, OperatorDetails},
};

pub fn get_operator_details(operator: Operator) -> OperatorDetails {
    match operator {
        Operator::Brava => OperatorDetails {
            realname: "Nayara Cardoso".to_string(),
            birthplace: "Curitiba, Brazil".to_string(),
            age: 40,
            date_of_birth: "January 10th".to_string(),
            season_introduced: Season::Y8S1,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "S.A.T".to_string(),
            country_code: "BR".to_string(),
            roles: vec![Role::IntelGatherer, Role::AntiGadget],
            side: Side::Attacker,
        },
        Operator::Solis => OperatorDetails {
            realname: "Ana Valentina Díaz".to_string(),
            birthplace: "Zipaquirá, Colombia".to_string(),
            age: 37,
            date_of_birth: "September 18th".to_string(),
            season_introduced: Season::Y7S4,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "AFEAU".to_string(),
            country_code: "CO".to_string(),
            roles: vec![Role::IntelGatherer],
            side: Side::Defender,
        },
        Operator::Grim => OperatorDetails {
            realname: "Charlie Tho Keng Boon".to_string(),
            birthplace: "Jurong, Singapore".to_string(),
            age: 39,
            date_of_birth: "April 5th".to_string(),
            season_introduced: Season::Y7S3,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "Nighthaven".to_string(),
            country_code: "".to_string(),
            roles: vec![Role::IntelGatherer, Role::AreaDenial],
            side: Side::Attacker,
        },
        Operator::Sens => OperatorDetails {
            realname: "Néon Ngoma Mutombo".to_string(),
            birthplace: "Brussels, Belgium".to_string(),
            age: 30,
            date_of_birth: "March 3rd".to_string(),
            season_introduced: Season::Y7S2,
            health: Health::High,
            speed: Speed::Slow,
            unit: "SFG".to_string(),
            country_code: "BE".to_string(),
            roles: vec![Role::CoveringFire, Role::AreaDenial, Role::CrowdControl],
            side: Side::Attacker,
        },
        Operator::Azami => OperatorDetails {
            realname: "Kana Fujiwara".to_string(),
            birthplace: "Kyoto, Japan".to_string(),
            age: 28,
            date_of_birth: "September 6th".to_string(),
            season_introduced: Season::Y7S1,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "UNAFFILIATED".to_string(),
            country_code: "JP".to_string(),
            roles: vec![Role::AreaDenial],
            side: Side::Defender,
        },
        Operator::Thorn => OperatorDetails {
            realname: "Brianna Skehan".to_string(),
            birthplace: "County Kildare, Ireland".to_string(),
            age: 28,
            date_of_birth: "June 18th".to_string(),
            season_introduced: Season::Y6S4,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "GARDA SÍOCHÁNA".to_string(),
            country_code: "IE".to_string(),
            roles: vec![Role::Anchor, Role::Secure],
            side: Side::Defender,
        },
        Operator::Osa => OperatorDetails {
            realname: "Anja Katarina Janković".to_string(),
            birthplace: "Split, Croatia".to_string(),
            age: 27,
            date_of_birth: "April 29th".to_string(),
            season_introduced: Season::Y6S3,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "NIGHTHAVEN".to_string(),
            country_code: "HR".to_string(),
            roles: vec![Role::IntelGatherer, Role::AreaDenial, Role::AntiRoam],
            side: Side::Attacker,
        },
        Operator::Thunderbird => OperatorDetails {
            realname: "Mina Sky".to_string(),
            birthplace: "Nakoda Territories".to_string(),
            age: 36,
            date_of_birth: "April 1st".to_string(),
            season_introduced: Season::Y6S2,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "UNAFFILIATED".to_string(),
            country_code: "".to_string(),
            roles: vec![Role::Secure, Role::Roam, Role::Buff],
            side: Side::Defender,
        },
        Operator::Flores => OperatorDetails {
            realname: "Santiago Miguel Lucero".to_string(),
            birthplace: "Buenos Aires, Argentina".to_string(),
            age: 38,
            date_of_birth: "April 1st".to_string(),
            season_introduced: Season::Y6S1,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "UNAFFILIATED".to_string(),
            country_code: "AR".to_string(),
            roles: vec![
                Role::SoftBreach,
                Role::Disable,
                Role::AreaDenial,
                Role::BackLine,
            ],
            side: Side::Attacker,
        },
        Operator::Aruni => OperatorDetails {
            realname: "Apha Tawanroong".to_string(),
            birthplace: "Ta Phraya District, Thailand".to_string(),
            age: 42,
            date_of_birth: "August 9th".to_string(),
            season_introduced: Season::Y5S4,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "NIGHTHAVEN".to_string(),
            country_code: "TH".to_string(),
            roles: vec![Role::Secure, Role::IntelGatherer, Role::Anchor],
            side: Side::Defender,
        },
        Operator::Zero => OperatorDetails {
            realname: "Samuel Leo Fisher".to_string(),
            birthplace: "Baltimore, Maryland".to_string(),
            age: 63,
            date_of_birth: "August 8th".to_string(),
            season_introduced: Season::Y5S3,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "ROS".to_string(),
            country_code: "US".to_string(),
            roles: vec![Role::IntelDenier, Role::IntelGatherer],
            side: Side::Attacker,
        },
        Operator::Ace => OperatorDetails {
            realname: "Håvard Haugland".to_string(),
            birthplace: "Lærdalsøyri, Norway".to_string(),
            age: 33,
            date_of_birth: "March 15th".to_string(),
            season_introduced: Season::Y5S2,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "NIGHTHAVEN".to_string(),
            country_code: "NO".to_string(),
            roles: vec![Role::FrontLine, Role::HardBreach],
            side: Side::Attacker,
        },
        Operator::Melusi => OperatorDetails {
            realname: "Thandiwe Ndlovu".to_string(),
            birthplace: "Louwsburg, South Africa".to_string(),
            age: 32,
            date_of_birth: "June 16th".to_string(),
            season_introduced: Season::Y5S2,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "ITF".to_string(),
            country_code: "SA".to_string(),
            roles: vec![Role::CrowdControl, Role::IntelGatherer, Role::Secure],
            side: Side::Defender,
        },
        Operator::Oryx => OperatorDetails {
            realname: "Saif Al Hadid".to_string(),
            birthplace: "Azraq, Jordan".to_string(),
            age: 45,
            date_of_birth: "July 3rd".to_string(),
            season_introduced: Season::Y5S1,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "UNAFFILIATED".to_string(),
            country_code: "JO".to_string(),
            roles: vec![Role::Roam, Role::SoftBreach],
            side: Side::Defender,
        },
        Operator::Iana => OperatorDetails {
            realname: "Nienke Meijer".to_string(),
            birthplace: "Katwijk, the Netherlands".to_string(),
            age: 35,
            date_of_birth: "August 27th".to_string(),
            season_introduced: Season::Y5S1,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "REU".to_string(),
            country_code: "NL".to_string(),
            roles: vec![Role::IntelDenier, Role::IntelGatherer],
            side: Side::Attacker,
        },
        Operator::Wamai => OperatorDetails {
            realname: "Ngũgĩ Muchoki Furaha".to_string(),
            birthplace: "Lamu, Kenya".to_string(),
            age: 28,
            date_of_birth: "June 1st".to_string(),
            season_introduced: Season::Y4S4,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "NIGHTHAVEN".to_string(),
            country_code: "KE".to_string(),
            roles: vec![Role::Anchor, Role::Secure],
            side: Side::Defender,
        },
        Operator::Kali => OperatorDetails {
            realname: "Jaimini Kalimohan Shah".to_string(),
            birthplace: "Amreli, India".to_string(),
            age: 34,
            date_of_birth: "August 21st".to_string(),
            season_introduced: Season::Y4S4,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "NIGHTHAVEN".to_string(),
            country_code: "IN".to_string(),
            roles: vec![Role::BackLine, Role::CoveringFire, Role::Disable],
            side: Side::Attacker,
        },
        Operator::Amaru => OperatorDetails {
            realname: "Azucena Rocío Quispe".to_string(),
            birthplace: "Cojata, Peru".to_string(),
            age: 48,
            date_of_birth: "May 6th".to_string(),
            season_introduced: Season::Y4S3,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "APCA".to_string(),
            country_code: "PE".to_string(),
            roles: vec![Role::Flank, Role::FrontLine],
            side: Side::Attacker,
        },
        Operator::Goyo => OperatorDetails {
            realname: "César Ruiz Hernández".to_string(),
            birthplace: "Culiacán Rosales, Mexico".to_string(),
            age: 31,
            date_of_birth: "June 20th".to_string(),
            season_introduced: Season::Y4S3,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "FES".to_string(),
            country_code: "MX".to_string(),
            roles: vec![Role::AreaDenial, Role::Secure],
            side: Side::Defender,
        },
        Operator::Nøkk => OperatorDetails {
            realname: "REDACTED".to_string(),
            birthplace: "REDACTED".to_string(),
            age: 00,
            date_of_birth: "REDACTED".to_string(),
            season_introduced: Season::Y4S2,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "JAEGER CORPS".to_string(),
            country_code: "DK".to_string(),
            roles: vec![Role::Flank, Role::IntelDenier],
            side: Side::Attacker,
        },
        Operator::Warden => OperatorDetails {
            realname: "Collinn McKinley".to_string(),
            birthplace: "Louisville, Kentucky".to_string(),
            age: 48,
            date_of_birth: "March 18th".to_string(),
            season_introduced: Season::Y4S2,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "SECRET SERVICE".to_string(),
            country_code: "US".to_string(),
            roles: vec![Role::Anchor, Role::IntelDenier],
            side: Side::Defender,
        },
        Operator::Mozzie => OperatorDetails {
            realname: "Max Goose".to_string(),
            birthplace: "Portland, Australia".to_string(),
            age: 35,
            date_of_birth: "February 15th".to_string(),
            season_introduced: Season::Y4S1,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "SASR".to_string(),
            country_code: "AN".to_string(),
            roles: vec![Role::IntelDenier, Role::IntelGatherer, Role::Secure],
            side: Side::Defender,
        },
        Operator::Gridlock => OperatorDetails {
            realname: "Tori Tallyo Fairous".to_string(),
            birthplace: "Longreach, Central Queensland, Australia".to_string(),
            age: 36,
            date_of_birth: "August 5th".to_string(),
            season_introduced: Season::Y4S1,
            health: Health::High,
            speed: Speed::Slow,
            unit: "SASR".to_string(),
            country_code: "AN".to_string(),
            roles: vec![Role::AntiRoam, Role::AreaDenial, Role::CrowdControl],
            side: Side::Attacker,
        },
        Operator::Nomad => OperatorDetails {
            realname: "Sanaa El Maktoub".to_string(),
            birthplace: "Marrakesh, Morocco".to_string(),
            age: 39,
            date_of_birth: "July 27th".to_string(),
            season_introduced: Season::Y3S4,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "GIGR".to_string(),
            country_code: "MA".to_string(),
            roles: vec![Role::AntiRoam, Role::CrowdControl, Role::Trap],
            side: Side::Attacker,
        },
        Operator::Kaid => OperatorDetails {
            realname: "Jalal El Fassi".to_string(),
            birthplace: "Aroumd, Morocco".to_string(),
            age: 58,
            date_of_birth: "June 26th".to_string(),
            season_introduced: Season::Y3S4,
            health: Health::High,
            speed: Speed::Slow,
            unit: "GIGR".to_string(),
            country_code: "MA".to_string(),
            roles: vec![Role::Anchor, Role::AntiHardBreach, Role::Secure],
            side: Side::Defender,
        },
        Operator::Clash => OperatorDetails {
            realname: "Morowa Evans".to_string(),
            birthplace: "London, England".to_string(),
            age: 35,
            date_of_birth: "June 7th".to_string(),
            season_introduced: Season::Y3S3,
            health: Health::High,
            speed: Speed::Slow,
            unit: "MPS".to_string(),
            country_code: "GB".to_string(),
            roles: vec![
                Role::CrowdControl,
                Role::IntelGatherer,
                Role::Secure,
                Role::Shield,
            ],
            side: Side::Defender,
        },
        Operator::Maverick => OperatorDetails {
            realname: "Erik Thorn".to_string(),
            birthplace: "Boston, Massachusetts".to_string(),
            age: 36,
            date_of_birth: "April 20th".to_string(),
            season_introduced: Season::Y3S3,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "THE UNIT".to_string(),
            country_code: "US".to_string(),
            roles: vec![Role::BackLine, Role::Disable, Role::Flank, Role::HardBreach],
            side: Side::Attacker,
        },
        Operator::Maestro => OperatorDetails {
            realname: "Adriano Martello".to_string(),
            birthplace: "Rome, Italy".to_string(),
            age: 45,
            date_of_birth: "April 13th".to_string(),
            season_introduced: Season::Y3S2,
            health: Health::High,
            speed: Speed::Slow,
            unit: "G.I.S.".to_string(),
            country_code: "IT".to_string(),
            roles: vec![
                Role::Anchor,
                Role::AreaDenial,
                Role::IntelGatherer,
                Role::Secure,
            ],
            side: Side::Defender,
        },
        Operator::Alibi => OperatorDetails {
            realname: "Aria de Luca".to_string(),
            birthplace: "Tripoli, Libya".to_string(),
            age: 37,
            date_of_birth: "December 15th".to_string(),
            season_introduced: Season::Y3S2,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "G.I.S.".to_string(),
            country_code: "IT".to_string(),
            roles: vec![
                Role::IntelDenier,
                Role::IntelGatherer,
                Role::Roam,
                Role::Trap,
            ],
            side: Side::Defender,
        },
        Operator::Lion => OperatorDetails {
            realname: "Olivier Flament".to_string(),
            birthplace: "Toulouse, France".to_string(),
            age: 31,
            date_of_birth: "August 29th".to_string(),
            season_introduced: Season::Y3S1,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "GIGN".to_string(),
            country_code: "FR".to_string(),
            roles: vec![
                Role::AntiRoam,
                Role::BackLine,
                Role::CrowdControl,
                Role::IntelGatherer,
            ],
            side: Side::Attacker,
        },
        Operator::Finka => OperatorDetails {
            realname: "Lera Melnikova".to_string(),
            birthplace: "Gomel, Belarus".to_string(),
            age: 32,
            date_of_birth: "June 7".to_string(),
            season_introduced: Season::Y3S1,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "SPETSNAZ".to_string(),
            country_code: "RU".to_string(),
            roles: vec![Role::BackLine, Role::Buff],
            side: Side::Attacker,
        },
        Operator::Vigil => OperatorDetails {
            realname: "Chul Kyung Hwa".to_string(),
            birthplace: "REDACTED".to_string(),
            age: 0,
            date_of_birth: "January 17th".to_string(),
            season_introduced: Season::Y2S4,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "07TH SMB".to_string(),
            country_code: "SK".to_string(),
            roles: vec![Role::IntelDenier, Role::Roam],
            side: Side::Defender,
        },
        Operator::Dokkaebi => OperatorDetails {
            realname: "Grace Nam".to_string(),
            birthplace: "Seoul, South Korea".to_string(),
            age: 29,
            date_of_birth: "February 2nd".to_string(),
            season_introduced: Season::Y2S4,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "707TH SMB".to_string(),
            country_code: "SK".to_string(),
            roles: vec![
                Role::AntiRoam,
                Role::Flank,
                Role::IntelDenier,
                Role::IntelGatherer,
            ],
            side: Side::Attacker,
        },
        Operator::Zofia => OperatorDetails {
            realname: "Zofia Bosak".to_string(),
            birthplace: "Wrocław, Poland".to_string(),
            age: 36,
            date_of_birth: "January 28th".to_string(),
            season_introduced: Season::Y2S4,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "G.R.O.".to_string(),
            country_code: "PL".to_string(),
            roles: vec![
                Role::AntiRoam,
                Role::CrowdControl,
                Role::Disable,
                Role::Flank,
                Role::SoftBreach,
            ],
            side: Side::Attacker,
        },
        Operator::Ela => OperatorDetails {
            realname: "Elżbieta Bosak".to_string(),
            birthplace: "Wrocław, Poland".to_string(),
            age: 31,
            date_of_birth: "November 8th".to_string(),
            season_introduced: Season::Y2S4,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "G.R.O.".to_string(),
            country_code: "PL".to_string(),
            roles: vec![Role::CrowdControl, Role::Roam, Role::Trap],
            side: Side::Defender,
        },
        Operator::Ying => OperatorDetails {
            realname: "Siu Mei Lin".to_string(),
            birthplace: "Hong Kong, Central".to_string(),
            age: 33,
            date_of_birth: "May 12th".to_string(),
            season_introduced: Season::Y2S3,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "S.D.U".to_string(),
            country_code: "HK".to_string(),
            roles: vec![Role::CrowdControl, Role::FrontLine],
            side: Side::Attacker,
        },
        Operator::Lesion => OperatorDetails {
            realname: "Liu Tze Long".to_string(),
            birthplace: "Hong Kong, Junk Bay (Tseung Kwan O)".to_string(),
            age: 44,
            date_of_birth: "July 2nd".to_string(),
            season_introduced: Season::Y2S3,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "S.D.U".to_string(),
            country_code: "HK".to_string(),
            roles: vec![
                Role::Anchor,
                Role::CrowdControl,
                Role::IntelGatherer,
                Role::Roam,
                Role::Trap,
            ],
            side: Side::Defender,
        },
        Operator::Mira => OperatorDetails {
            realname: "Elena María Álvarez".to_string(),
            birthplace: "Madrid, Spain".to_string(),
            age: 39,
            date_of_birth: "November 18th".to_string(),
            season_introduced: Season::Y2S1,
            health: Health::High,
            speed: Speed::Slow,
            unit: "G.E.O.".to_string(),
            country_code: "ES".to_string(),
            roles: vec![Role::Anchor, Role::IntelGatherer, Role::Secure],
            side: Side::Defender,
        },
        Operator::Jackal => OperatorDetails {
            realname: "Ryad Ramírez Al-Hassar".to_string(),
            birthplace: "Ceuta, Spain".to_string(),
            age: 49,
            date_of_birth: "February 29th".to_string(),
            season_introduced: Season::Y2S1,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "G.E.O.".to_string(),
            country_code: "ES".to_string(),
            roles: vec![Role::AntiRoam, Role::IntelGatherer],
            side: Side::Attacker,
        },
        Operator::Hibana => OperatorDetails {
            realname: "Yumiko Imagawa".to_string(),
            birthplace: "Nagoya, Japan".to_string(),
            age: 34,
            date_of_birth: "July 12th".to_string(),
            season_introduced: Season::Y1S4,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "S.A.T.".to_string(),
            country_code: "JP".to_string(),
            roles: vec![Role::BackLine, Role::FrontLine, Role::HardBreach],
            side: Side::Attacker,
        },
        Operator::Echo => OperatorDetails {
            realname: "Masaru Enatsu".to_string(),
            birthplace: "Tokyo, Japan (Suginami-ku)".to_string(),
            age: 36,
            date_of_birth: "October 31st".to_string(),
            season_introduced: Season::Y1S4,
            health: Health::High,
            speed: Speed::Slow,
            unit: "S.A.T.".to_string(),
            country_code: "JP".to_string(),
            roles: vec![
                Role::Anchor,
                Role::CrowdControl,
                Role::IntelGatherer,
                Role::Secure,
            ],
            side: Side::Defender,
        },
        Operator::Caveira => OperatorDetails {
            realname: "Taina Pereira".to_string(),
            birthplace: "Rinópolis, Brazil".to_string(),
            age: 27,
            date_of_birth: "October 15th".to_string(),
            season_introduced: Season::Y1S3,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "BOPE".to_string(),
            country_code: "BR".to_string(),
            roles: vec![Role::IntelDenier, Role::IntelGatherer, Role::Roam],
            side: Side::Defender,
        },
        Operator::Capitão => OperatorDetails {
            realname: "Vicente Souza".to_string(),
            birthplace: "Rio de Janeiro, Brazil (Nova Iguaçu)".to_string(),
            age: 49,
            date_of_birth: "November 17th".to_string(),
            season_introduced: Season::Y1S3,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "BOPE".to_string(),
            country_code: "BR".to_string(),
            roles: vec![Role::AreaDenial, Role::Flank, Role::FrontLine],
            side: Side::Attacker,
        },
        Operator::Blackbeard => OperatorDetails {
            realname: "Craig Jenson".to_string(),
            birthplace: "Bellevue, Washington".to_string(),
            age: 32,
            date_of_birth: "March 12th".to_string(),
            season_introduced: Season::Y1S2,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "NAVY SEAL".to_string(),
            country_code: "US".to_string(),
            roles: vec![Role::BackLine, Role::CoveringFire, Role::Shield],
            side: Side::Attacker,
        },
        Operator::Valkyrie => OperatorDetails {
            realname: "Meghan J. Castellano".to_string(),
            birthplace: "Oceaside, California".to_string(),
            age: 31,
            date_of_birth: "July 21st".to_string(),
            season_introduced: Season::Y1S2,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "NAVY SEAL".to_string(),
            country_code: "US".to_string(),
            roles: vec![Role::IntelGatherer, Role::Roam],
            side: Side::Defender,
        },
        Operator::Buck => OperatorDetails {
            realname: "Sebastien Côté".to_string(),
            birthplace: "Montreal, QC".to_string(),
            age: 36,
            date_of_birth: "August 20th".to_string(),
            season_introduced: Season::Y1S1,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "JTF2".to_string(),
            country_code: "CA".to_string(),
            roles: vec![Role::Flank, Role::SoftBreach],
            side: Side::Attacker,
        },
        Operator::Frost => OperatorDetails {
            realname: "Tina Lin Tsang".to_string(),
            birthplace: "Vancouver, British Columbia".to_string(),
            age: 32,
            date_of_birth: "May 4th".to_string(),
            season_introduced: Season::Y1S1,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "JTF2".to_string(),
            country_code: "CA".to_string(),
            roles: vec![Role::CrowdControl, Role::Trap],
            side: Side::Defender,
        },
        Operator::Mute => OperatorDetails {
            realname: "Mark R. Chandar".to_string(),
            birthplace: "York, England".to_string(),
            age: 25,
            date_of_birth: "October 11th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "SAS".to_string(),
            country_code: "GB".to_string(),
            roles: vec![Role::AntiHardBreach, Role::IntelDenier, Role::Secure],
            side: Side::Defender,
        },
        Operator::Sledge => OperatorDetails {
            realname: "Seamus Cowden".to_string(),
            birthplace: "John O’Groats, Scotland".to_string(),
            age: 35,
            date_of_birth: "April 2nd".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "SAS".to_string(),
            country_code: "GB".to_string(),
            roles: vec![Role::Flank, Role::SoftBreach],
            side: Side::Attacker,
        },
        Operator::Smoke => OperatorDetails {
            realname: "James Porter".to_string(),
            birthplace: "London, England (King's Cross)".to_string(),
            age: 36,
            date_of_birth: "May 14th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "SAS".to_string(),
            country_code: "GB".to_string(),
            roles: vec![Role::Anchor, Role::AreaDenial, Role::Secure],
            side: Side::Defender,
        },
        Operator::Thatcher => OperatorDetails {
            realname: "Mike Baker".to_string(),
            birthplace: "Bideford, England".to_string(),
            age: 56,
            date_of_birth: "June 22nd".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "SAS".to_string(),
            country_code: "GB".to_string(),
            roles: vec![Role::BackLine, Role::Disable],
            side: Side::Attacker,
        },
        Operator::Ash => OperatorDetails {
            realname: "Eliza Cohen".to_string(),
            birthplace: "Jerusalem, Israel".to_string(),
            age: 33,
            date_of_birth: "December 24th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "SWAT".to_string(),
            country_code: "US".to_string(),
            roles: vec![
                Role::Disable,
                Role::Flank,
                Role::FrontLine,
                Role::SoftBreach,
            ],
            side: Side::Attacker,
        },
        Operator::Castle => OperatorDetails {
            realname: "Miles Campbell".to_string(),
            birthplace: "Sherman Oaks, California".to_string(),
            age: 36,
            date_of_birth: "September 20th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "SWAT".to_string(),
            country_code: "US".to_string(),
            roles: vec![Role::Anchor, Role::Secure],
            side: Side::Defender,
        },
        Operator::Pulse => OperatorDetails {
            realname: "Jack Estrada".to_string(),
            birthplace: "Goldsboro, North Carolina".to_string(),
            age: 32,
            date_of_birth: "October 11th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "SWAT".to_string(),
            country_code: "US".to_string(),
            roles: vec![Role::IntelGatherer, Role::Roam],
            side: Side::Defender,
        },
        Operator::Thermite => OperatorDetails {
            realname: "Jordan Trace".to_string(),
            birthplace: "Plano, Texas".to_string(),
            age: 35,
            date_of_birth: "March 14th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "SWAT".to_string(),
            country_code: "US".to_string(),
            roles: vec![Role::BackLine, Role::HardBreach],
            side: Side::Attacker,
        },
        Operator::Montagne => OperatorDetails {
            realname: "Gilles Touré".to_string(),
            birthplace: "Bordeaux, France".to_string(),
            age: 48,
            date_of_birth: "October 11th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::High,
            speed: Speed::Slow,
            unit: "GIGN".to_string(),
            country_code: "FR".to_string(),
            roles: vec![Role::Shield],
            side: Side::Attacker,
        },
        Operator::Twitch => OperatorDetails {
            realname: "Emmanuelle Pichon".to_string(),
            birthplace: "ancy, France".to_string(),
            age: 28,
            date_of_birth: "October 12th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "GIGN".to_string(),
            country_code: "FR".to_string(),
            roles: vec![
                Role::BackLine,
                Role::Disable,
                Role::FrontLine,
                Role::IntelGatherer,
            ],
            side: Side::Attacker,
        },
        Operator::Doc => OperatorDetails {
            realname: "Gustave Kateb".to_string(),
            birthplace: "aris, France".to_string(),
            age: 39,
            date_of_birth: "September 16th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::High,
            speed: Speed::Slow,
            unit: "GIGN".to_string(),
            country_code: "FR".to_string(),
            roles: vec![Role::Anchor, Role::Buff],
            side: Side::Defender,
        },
        Operator::Rook => OperatorDetails {
            realname: "Julien Nizan".to_string(),
            birthplace: "Tours, France".to_string(),
            age: 27,
            date_of_birth: "January 6th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::High,
            speed: Speed::Slow,
            unit: "GIGN".to_string(),
            country_code: "FR".to_string(),
            roles: vec![Role::Anchor, Role::Buff],
            side: Side::Defender,
        },
        Operator::Jäger => OperatorDetails {
            realname: "Marius Streicher".to_string(),
            birthplace: "Düsseldorf, Germany".to_string(),
            age: 39,
            date_of_birth: "March 9th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "GSG9".to_string(),
            country_code: "DE".to_string(),
            roles: vec![Role::Roam, Role::Secure],
            side: Side::Defender,
        },
        Operator::Bandit => OperatorDetails {
            realname: "Dominic Brunsmeier".to_string(),
            birthplace: "Berlin, Germany".to_string(),
            age: 42,
            date_of_birth: "August 13th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "GSG9".to_string(),
            country_code: "DE".to_string(),
            roles: vec![Role::AntiHardBreach, Role::Roam, Role::Secure],
            side: Side::Defender,
        },
        Operator::Blitz => OperatorDetails {
            realname: "Elias Kötz".to_string(),
            birthplace: "Bremen, Germany".to_string(),
            age: 37,
            date_of_birth: "April 2nd".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "GSG9".to_string(),
            country_code: "DE".to_string(),
            roles: vec![
                Role::AntiRoam,
                Role::CrowdControl,
                Role::FrontLine,
                Role::Shield,
            ],
            side: Side::Attacker,
        },
        Operator::Iq => OperatorDetails {
            realname: "Monika Weiss".to_string(),
            birthplace: "Leipzig, Germany".to_string(),
            age: 38,
            date_of_birth: "August 1st".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "GSG9".to_string(),
            country_code: "DE".to_string(),
            roles: vec![
                Role::Disable,
                Role::Flank,
                Role::FrontLine,
                Role::IntelGatherer,
            ],
            side: Side::Attacker,
        },
        Operator::Fuze => OperatorDetails {
            realname: "Shuhrat Kessikbayev".to_string(),
            birthplace: "Samarkand, Uzbekistan".to_string(),
            age: 39,
            date_of_birth: "October 12th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::High,
            speed: Speed::Slow,
            unit: "SPETSNAZ".to_string(),
            country_code: "RU".to_string(),
            roles: vec![Role::AreaDenial, Role::Disable, Role::Flank],
            side: Side::Attacker,
        },
        Operator::Glaz => OperatorDetails {
            realname: "Timur Glazkov".to_string(),
            birthplace: "Vladivostok, Primorsky Krai, Russia".to_string(),
            age: 34,
            date_of_birth: "July 2nd".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Low,
            speed: Speed::Fast,
            unit: "SPETSNAZ".to_string(),
            country_code: "RU".to_string(),
            roles: vec![Role::BackLine, Role::CoveringFire, Role::SoftBreach],
            side: Side::Attacker,
        },
        Operator::Tachanka => OperatorDetails {
            realname: "Alexsandr Senaviev".to_string(),
            birthplace: "Saint Petersburg, Russia".to_string(),
            age: 54,
            date_of_birth: "November 3rd".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::High,
            speed: Speed::Slow,
            unit: "SPETSNAZ".to_string(),
            country_code: "RU".to_string(),
            roles: vec![Role::Anchor, Role::CoveringFire, Role::Shield],
            side: Side::Defender,
        },
        Operator::Kapkan => OperatorDetails {
            realname: "Maxim Basuda".to_string(),
            birthplace: "Kovrov, Vladimir Oblast, Russia".to_string(),
            age: 42,
            date_of_birth: "May 14th".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Medium,
            speed: Speed::Normal,
            unit: "SPETSNAZ".to_string(),
            country_code: "RU".to_string(),
            roles: vec![Role::Trap],
            side: Side::Defender,
        },

        Operator::Recruit => OperatorDetails {
            realname: "Unknown".to_string(),
            birthplace: "Unknown".to_string(),
            age: 0,
            date_of_birth: "Unknown".to_string(),
            season_introduced: Season::Y0S0,
            health: Health::Low,
            speed: Speed::Slow,
            unit: "UNAFFILIATED".to_string(),
            country_code: "".to_string(),
            roles: vec![],
            side: Side::Defender,
        },
    }
}
