on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.rs'
      - '**/Cargo.*'
      - 'Dockerfile'


name: changelog
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  changelog:
    runs-on: ubuntu-latest
    name: check changelog
    steps:
      - uses: actions/checkout@v4
      - uses: Zomzog/changelog-checker@v1.3.0
        with:
          fileName: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
